"""Create the relationship between room and server

Revision ID: 2336342b2faa
Revises: 83c78348fe12
Create Date: 2025-11-04 12:54:47.118897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2336342b2faa'
down_revision: Union[str, Sequence[str], None] = '83c78348fe12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('server_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'room', 'server', ['server_id'], ['id'])
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=1)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_column('room', 'server_id')
    # ### end Alembic commands ###
